name: Docker Build

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04

    env:
      IMAGE_NAME: yanyi/generate-multifields
      BUILD_SHA: ${{ github.sha }}

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: Build Docker image (PRs)
        if: endsWith(github.ref, '/develop') == false
        run: |
          export CLI_VERSION=pr-$(echo "$GITHUB_REF" | awk -F / '{print $3}')
          echo "Building Docker image with $IMAGE_NAME:$CLI_VERSION with $BUILD_SHA"
          docker build \
            --build-arg CLI_VERSION=$CLI_VERSION \
            --build-arg BUILD_SHA=$BUILD_SHA \
            -t $IMAGE_NAME:$CLI_VERSION .

      - name: Print CLI version (PRs)
        if: endsWith(github.ref, '/develop') == false
        run: |
          export CLI_VERSION=pr-$(echo "$GITHUB_REF" | awk -F / '{print $3}')
          docker run --rm $IMAGE_NAME:$CLI_VERSION version

      - name: Build Docker image (Staging)
        if: endsWith(github.ref, '/develop')
        env:
          CLI_VERSION: staging
        run: |
          echo $IMAGE_NAME:staging - $BUILD_SHA
