name: Docker Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    env:
      IMAGE_NAME: yanyi/generate-multifields
      BUILD_SHA: ${{ github.sha }}

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: Set Docker tag
        run: |
          echo ::set-env name=IMAGE_TAG::pr-$(echo "$GITHUB_REF" | awk -F / '{print $3}')

      - name: Build Docker image
        if: endsWith(github.ref, '/master') == false
        run: |
          echo "Building Docker image with ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}, commit ${{ env.BUILD_SHA }}."
          docker build \
            --build-arg CLI_VERSION=${{ env.IMAGE_TAG }} \
            --build-arg BUILD_SHA=${{ env.BUILD_SHA }} \
            -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Print CLI version
        if: endsWith(github.ref, '/master') == false
        run: docker run --rm ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} version
