name: Docker Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    env:
      IMAGE_NAME: yanyi/generate-multifields
      BUILD_SHA: ${{ github.sha }}

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: Set Docker tag
        run: |
          echo ::set-env name=IMAGE_TAG::pr-$(echo "$GITHUB_REF" | awk -F / '{print $3}')

      - name: Build Docker image
        if: endsWith(github.ref, '/develop') == false
        run: |
          echo "Building Docker image with $IMAGE_NAME:$IMAGE_TAG with $BUILD_SHA"
          docker build \
            --build-arg CLI_VERSION=$IMAGE_TAG \
            --build-arg BUILD_SHA=$BUILD_SHA \
            -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Print CLI version
        if: endsWith(github.ref, '/develop') == false
        run: |
          docker run --rm $IMAGE_NAME:$IMAGE_TAG version
