name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: Setup Go for use with actions
        uses: actions/setup-go@v1.0.0
        with:
          version: 1.13.9

      - name: Go cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run Go tests
        run: go test -cover -v ./...
